"""add conversations

Revision ID: 8bf39b64a5e4
Revises: ca3058465e62
Create Date: 2026-10-02 18:56:55.775602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bf39b64a5e4'
down_revision: Union[str, Sequence[str], None] = 'ca3058465e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Added by hand: the old single-conversation history is dropped, since existing rows
    # would have no value for the new NOT NULL conversation_id / seq columns.
    op.execute("DELETE FROM messages")
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('seq', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_unique_constraint('uq_messages_conversation_id_seq', ['conversation_id', 'seq'])
        batch_op.create_foreign_key('fk_messages_conversation_id', 'conversations', ['conversation_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_conversation_id', type_='foreignkey')
        batch_op.drop_constraint('uq_messages_conversation_id_seq', type_='unique')
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))
        batch_op.drop_column('seq')
        batch_op.drop_column('conversation_id')

    op.drop_table('conversations')
    # ### end Alembic commands ###
